name: PureEntitiesX
main: revivalpmmp\pureentities\PureEntities
version: 0.2.4_dev
api: [3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7]

load: STARTUP
authors: ["milk0417", "RevivalPMMP"]
description: Implement all MCPE entities into your worlds
website: https://github.com/RevivalPMMP/PureEntitiesX

commands:
  pesummon:
    description: Summons a creature
    usage: "/pesummon <mob-name> [playername] [isBaby(true|false)]"
    permission: pureentities.command.pesummon
  peremove:
    description: Removes all entities from the current level
    usage: "/peremove"
    permission: pureentities.command.peremove

permissions:
 pureentities:
  default: op
  description: "Allows using all the PureEntities commands"
  children:
    pureentities.command:
    default: op
    description: "Allows using all the PureEntities commands"
    children:
      pureentities.command.pesummon:
        default: op
        description: "Allows spawning mobs"
      pureentities.command.peremove:
        default: op
        description: "Allows remove of all entities in current level"
